# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: DialogBoxes.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

ID_THRESHOLD_TYPE = 10000
ID_THRESHOLD_MODE = 10001
ID_TEXT_LEVEL = 10002
ID_THRESHOLD = 10003
ID_THRESHOLD_SLIDER = 10004
ID_PERCENT_TEXT = 10005
ID_PERCENT = 10006

def ThresholdDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item2 = wx.RadioBox( parent, ID_THRESHOLD_TYPE, "Type", wx.DefaultPosition, wx.DefaultSize,
        ["Simple","Low Pass","High Pass   "] , 1, wx.RA_SPECIFY_COLS )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.RadioBox( parent, ID_THRESHOLD_MODE, "Mode", wx.DefaultPosition, wx.DefaultSize,
        ["Standard   ","Inverse"] , 1, wx.RA_SPECIFY_COLS )
    item3.SetToolTip( wx.ToolTip("standard or inverse video") )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.BoxSizer( wx.HORIZONTAL )

    item5 = wx.StaticText( parent, ID_TEXT_LEVEL, "level:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.TextCtrl( parent, ID_THRESHOLD, "", wx.DefaultPosition, [46,-1], 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item7 = wx.Slider( parent, ID_THRESHOLD_SLIDER, 0, 0, 255, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL )
    item4.Add( item7, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )

    item9 = wx.StaticText( parent, ID_PERCENT_TEXT, "% of pixels above threshold:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item10 = wx.TextCtrl( parent, ID_PERCENT, "", wx.DefaultPosition, [55,-1], wx.TE_READONLY )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item0.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.BoxSizer( wx.HORIZONTAL )

    item12 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetDefault()
    item11.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_ANGLE90 = 10007
ID_ANGLE180 = 10008
ID_ANGLE270 = 10009
ID_ANGLEOTHER = 10010
ID_ANGLE = 10011
ID_ANGLEFLIP = 10012
ID_ANGLEFLOP = 10013

def GeometricPage1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "angle selection" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )

    item3 = wx.RadioButton( parent, ID_ANGLE90, "90 degrees", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.RadioButton( parent, ID_ANGLE180, "180 degrees", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.RadioButton( parent, ID_ANGLE270, "270 degrees", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )

    item7 = wx.RadioButton( parent, ID_ANGLEOTHER, "Other angle:  ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.SHAPED, 5 )

    item8 = wx.TextCtrl( parent, ID_ANGLE, "", wx.DefaultPosition, [60,-1], 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER, 5 )

    item1.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 0 )

    item9 = wx.RadioButton( parent, ID_ANGLEFLIP, "Flip - horizontally", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item9, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item10 = wx.RadioButton( parent, ID_ANGLEFLOP, "Flop - vertically", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_TEXT = 10014
ID_TRANS_DISTANCE = 10015
ID_RADIOBOX2 = 10016

def GeometricPage2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.StaticText( parent, ID_TEXT, "roll distance: ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.TextCtrl( parent, ID_TRANS_DISTANCE, "", wx.DefaultPosition, [60,-1], 0 )
    item2.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.RadioBox( parent, ID_RADIOBOX2, "direction", wx.DefaultPosition, [90,-1],
        ["left","right","up","down"] , 1, wx.RA_SPECIFY_COLS )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, 0, 10 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_GEOMETRIC_DIALOG = 10017

def GeometricDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.Notebook( parent, ID_GEOMETRIC_DIALOG, wx.DefaultPosition, [220,220], 0 )
    if wx.VERSION >= (2,5,2):
        item1 = item2
    else:
        item1 = wx.NotebookSizer( item2 )

    item3 = wx.Panel( item2, -1 )
    GeometricPage1Func(item3, False)
    item2.AddPage( item3, "Rotate" )

    item4 = wx.Panel( item2, -1 )
    GeometricPage2Func(item4, False)
    item2.AddPage( item4, "Roll" )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )

    item6 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetDefault()
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_SCALE_UNITS = 10018
ID_UNITS_TEXT = 10019
ID_SCALE_PIXELS = 10020
ID_PIXEL_TEXT = 10021
ID_SCALE_TIME = 10022
ID_TIME_TEXT = 10023
ID_SAVE_SCALE_BUTTON = 10024
ID_LOAD_SCALE_BUTTON = 10025
ID_SCALE_RESET_BUTTON = 10026

def ScaleDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Spacial scale" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )

    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )

    item4 = wx.TextCtrl( parent, ID_SCALE_UNITS, "", wx.DefaultPosition, [60,-1], 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.StaticText( parent, ID_UNITS_TEXT, "user units", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.TextCtrl( parent, ID_SCALE_PIXELS, "", wx.DefaultPosition, [60,-1], 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item7 = wx.StaticText( parent, ID_PIXEL_TEXT, "image units", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE )
    item3.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.StaticBox( parent, -1, "Time scale" )
    item8 = wx.StaticBoxSizer( item9, wx.VERTICAL )

    item10 = wx.BoxSizer( wx.HORIZONTAL )

    item11 = wx.TextCtrl( parent, ID_SCALE_TIME, "", wx.DefaultPosition, [60,-1], 0 )
    item10.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item12 = wx.StaticText( parent, ID_TIME_TEXT, "frame rate (f/s)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item0.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.BoxSizer( wx.HORIZONTAL )

    item14 = wx.Button( parent, ID_SAVE_SCALE_BUTTON, "Save", wx.DefaultPosition, [50,-1], 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.Button( parent, ID_LOAD_SCALE_BUTTON, "Load", wx.DefaultPosition, [50,-1], 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item16 = wx.Button( parent, ID_SCALE_RESET_BUTTON, "Reset", wx.DefaultPosition, [50,-1], 0 )
    item13.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item13, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item17 = wx.BoxSizer( wx.HORIZONTAL )

    item18 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetDefault()
    item17.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_INTENSITY = 10027
ID_GRADIENT = 10028
ID_SECOND_DERIVATIVE = 10029
ID_EVEN_SPACING = 10030
ID_TOTAL_LENGTH = 10031
ID_FIXED = 10032
ID_NPOINTS = 10033
ID_VARIABLE = 10034
ID_RESULT_FORMAT = 10035
ID_VELOCITY_X = 10036
ID_VELOCITY_Y = 10037
ID_USE_VELOCITY = 10038
ID_TEXT_II = 10039
ID_IDEAL_INTENS = 10040
ID_TEXT_PIXSEARCH = 10041
ID_PIXELS_TO_SEARCH = 10042
ID_TEXT_IPR = 10043
ID_IPR = 10044
ID_RESET = 10045
ID_SLITHER = 10046

def SnakeDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.HORIZONTAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item3 = wx.StaticBox( parent, -1, "Energy function weights" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )

    item4 = wx.BoxSizer( wx.HORIZONTAL )

    item5 = wx.StaticText( parent, ID_TEXT, "Intensity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.TextCtrl( parent, ID_INTENSITY, "", wx.DefaultPosition, [50,23], 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item2.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )

    item8 = wx.StaticText( parent, ID_TEXT, "Gradient", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.TextCtrl( parent, ID_GRADIENT, "", wx.DefaultPosition, [50,23], 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item2.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0 )

    item10 = wx.BoxSizer( wx.HORIZONTAL )

    item11 = wx.StaticText( parent, ID_TEXT, "Second derivative", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item12 = wx.TextCtrl( parent, ID_SECOND_DERIVATIVE, "", wx.DefaultPosition, [50,23], 0 )
    item10.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item2.Add( item10, 0, wx.ALIGN_CENTER, 0 )

    item13 = wx.BoxSizer( wx.HORIZONTAL )

    item14 = wx.StaticText( parent, ID_TEXT, "Even spacing", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.TextCtrl( parent, ID_EVEN_SPACING, "", wx.DefaultPosition, [50,23], 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item2.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0 )

    item16 = wx.BoxSizer( wx.HORIZONTAL )

    item17 = wx.StaticText( parent, ID_TEXT, "Total length", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.TextCtrl( parent, ID_TOTAL_LENGTH, "", wx.DefaultPosition, [50,23], 0 )
    item16.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item2.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item20 = wx.StaticBox( parent, -1, "Snake points" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )

    item21 = wx.BoxSizer( wx.HORIZONTAL )

    item22 = wx.RadioButton( parent, ID_FIXED, "fixed number", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item21.Add( item22, 0, wx.ALIGN_CENTER|wx.RIGHT, 0 )

    item23 = wx.TextCtrl( parent, ID_NPOINTS, "", wx.DefaultPosition, [50,23], 0 )
    item21.Add( item23, 0, wx.ALIGN_CENTER|wx.LEFT, 0 )

    item19.Add( item21, 0, wx.ALIGN_CENTER_VERTICAL, 0 )

    item24 = wx.BoxSizer( wx.HORIZONTAL )

    item25 = wx.RadioButton( parent, ID_VARIABLE, "variable (%) ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item26 = wx.TextCtrl( parent, ID_PERCENT, "", wx.DefaultPosition, [50,23], 0 )
    item24.Add( item26, 0, wx.ALIGN_CENTER|wx.LEFT, 0 )

    item19.Add( item24, 0, wx.ALIGN_CENTER_VERTICAL, 0 )

    item1.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item27 = wx.RadioBox( parent, ID_RESULT_FORMAT, "Result format", wx.DefaultPosition, wx.DefaultSize,
        ["short - centroid/radius","long - points under line"] , 1, wx.RA_SPECIFY_COLS )
    item1.Add( item27, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item0.Add( item1, 0, wx.ALL, 5 )

    item28 = wx.BoxSizer( wx.VERTICAL )

    item30 = wx.StaticBox( parent, -1, "Velocity vector" )
    item29 = wx.StaticBoxSizer( item30, wx.VERTICAL )

    item31 = wx.BoxSizer( wx.HORIZONTAL )

    item32 = wx.StaticText( parent, ID_TEXT, "X velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item33 = wx.TextCtrl( parent, ID_VELOCITY_X, "", wx.DefaultPosition, [50,23], 0 )
    item31.Add( item33, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item29.Add( item31, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34 = wx.BoxSizer( wx.HORIZONTAL )

    item35 = wx.StaticText( parent, ID_TEXT, "Y velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.Add( item35, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.TextCtrl( parent, ID_VELOCITY_Y, "", wx.DefaultPosition, [50,23], 0 )
    item34.Add( item36, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item29.Add( item34, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item37 = wx.CheckBox( parent, ID_USE_VELOCITY, "use velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item37, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item28.Add( item29, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38 = wx.BoxSizer( wx.HORIZONTAL )

    item39 = wx.StaticText( parent, ID_TEXT_II, "Ideal intensity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item39, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item40 = wx.TextCtrl( parent, ID_IDEAL_INTENS, "", wx.DefaultPosition, [50,23], 0 )
    item38.Add( item40, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item28.Add( item38, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 10 )

    item41 = wx.BoxSizer( wx.HORIZONTAL )

    item42 = wx.StaticText( parent, ID_TEXT_PIXSEARCH, "Pixels to search", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item42, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item43 = wx.TextCtrl( parent, ID_PIXELS_TO_SEARCH, "", wx.DefaultPosition, [50,23], 0 )
    item41.Add( item43, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item28.Add( item41, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 0 )

    item44 = wx.BoxSizer( wx.HORIZONTAL )

    item45 = wx.StaticText( parent, ID_TEXT_IPR, "Processing Radius", wx.DefaultPosition, wx.DefaultSize, 0 )
    item44.Add( item45, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item46 = wx.TextCtrl( parent, ID_IPR, "", wx.DefaultPosition, [50,23], 0 )
    item44.Add( item46, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item28.Add( item44, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47 = wx.BoxSizer( wx.HORIZONTAL )

    item48 = wx.Button( parent, ID_RESET, "Reset", wx.DefaultPosition, [65,-1], 0 )
    item47.Add( item48, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item49 = wx.Button( parent, ID_SLITHER, "Slither", wx.DefaultPosition, [65,-1], 0 )
    item47.Add( item49, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item28.Add( item47, 0, wx.ALIGN_CENTER|wx.TOP, 25 )

    item50 = wx.BoxSizer( wx.HORIZONTAL )

    item51 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, [65,-1], 0 )
    item51.SetDefault()
    item50.Add( item51, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item52 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, [65,-1], 0 )
    item50.Add( item52, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item28.Add( item50, 0, wx.ALIGN_CENTER|wx.TOP, 0 )

    item0.Add( item28, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_RIGHT = 10047
ID_LEFT = 10048
ID_UP = 10049
ID_DOWN = 10050
ID_RADIO_ANGLE = 10051
ID_THRESH_CONSTRAIN = 10052
ID_SEARCH_TO_LINE = 10053
ID_SEARCH_AOI = 10054

def ThresholdTrackingDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.StaticBox( parent, -1, "Direction" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )

    item4 = wx.RadioButton( parent, ID_RIGHT, "right", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.RadioButton( parent, ID_LEFT, "left", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.RadioButton( parent, ID_UP, "up", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.RadioButton( parent, ID_DOWN, "down", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )

    item9 = wx.RadioButton( parent, ID_RADIO_ANGLE, "angle: ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.SHAPED, 5 )

    item10 = wx.TextCtrl( parent, ID_ANGLE, "", wx.DefaultPosition, [54,23], 0 )
    item8.Add( item10, 0, wx.ALIGN_CENTER, 5 )

    item2.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 0 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item11 = wx.BoxSizer( wx.VERTICAL )

    item13 = wx.StaticBox( parent, -1, "Velocity vector" )
    item12 = wx.StaticBoxSizer( item13, wx.VERTICAL )

    item14 = wx.BoxSizer( wx.HORIZONTAL )

    item15 = wx.StaticText( parent, ID_TEXT, "X velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.TextCtrl( parent, ID_VELOCITY_X, "", wx.DefaultPosition, [50,23], 0 )
    item14.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item12.Add( item14, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.BoxSizer( wx.HORIZONTAL )

    item18 = wx.StaticText( parent, ID_TEXT, "Y velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.TextCtrl( parent, ID_VELOCITY_Y, "", wx.DefaultPosition, [50,23], 0 )
    item17.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item12.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.CheckBox( parent, ID_USE_VELOCITY, "use velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item20, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item11.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item21 = wx.BoxSizer( wx.VERTICAL )

    item22 = wx.CheckBox( parent, ID_THRESH_CONSTRAIN, "Constrain AOI to line", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item22, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = wx.RadioButton( parent, ID_SEARCH_TO_LINE, "constrain search to line", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item21.Add( item23, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = wx.RadioButton( parent, ID_SEARCH_AOI, "allow full AOI search", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item24, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item11.Add( item21, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item1.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item25 = wx.BoxSizer( wx.HORIZONTAL )

    item26 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.SetDefault()
    item25.Add( item26, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item27 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item27, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item25, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_RADIO_FIRST = 10055
ID_GOTO_FIRST = 10056
ID_RADIO_LAST = 10057
ID_GOTO_LAST = 10058
ID_RADIO_SPECIFIC = 10059
ID_GOTO_SPECIFIC = 10060

def GotoFrameDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )

    item2 = wx.RadioButton( parent, ID_RADIO_FIRST, "Goto first frame", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item1.Add( item2, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3 = wx.TextCtrl( parent, ID_GOTO_FIRST, "", wx.DefaultPosition, [50,23], 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.RadioButton( parent, ID_RADIO_LAST, "Goto last frame", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.TextCtrl( parent, ID_GOTO_LAST, "", wx.DefaultPosition, [50,23], 0 )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item6 = wx.RadioButton( parent, ID_RADIO_SPECIFIC, "Goto specific frame", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item7 = wx.TextCtrl( parent, ID_GOTO_SPECIFIC, "", wx.DefaultPosition, [50,23], 0 )
    item1.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )

    item9 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetDefault()
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_CENTER_OF_MASS = 10061
ID_CENTER_GRAYSCALE = 10062
ID_FOUR_SIDE_EDGE = 10063
ID_SAVE0 = 10064
ID_SAVE1 = 10065
ID_SAVE2 = 10066
ID_CENTER_VELOCITY_X = 10067
ID_CENTER_VELOCITY_Y = 10068
ID_CENTER_USE_VELOCITY = 10069

def CenterTrackingDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item3 = wx.StaticBox( parent, -1, "Method" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )

    item4 = wx.RadioButton( parent, ID_CENTER_OF_MASS, "center of mass - threshold", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.RadioButton( parent, ID_CENTER_GRAYSCALE, "center of mass - grayscale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.RadioButton( parent, ID_FOUR_SIDE_EDGE, "four side edge - threshold only", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.BoxSizer( wx.VERTICAL )

    item9 = wx.StaticBox( parent, -1, "Save data to Results file" )
    item8 = wx.StaticBoxSizer( item9, wx.VERTICAL )

    item10 = wx.RadioButton( parent, ID_SAVE0, "center (x, y)", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item8.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item11 = wx.RadioButton( parent, ID_SAVE1, "center, width, height", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item12 = wx.RadioButton( parent, ID_SAVE2, "center, width, height, p0, p90, p180, p270", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item0.Add( item7, 0, wx.ALIGN_CENTER, 5 )

    item13 = wx.BoxSizer( wx.VERTICAL )

    item15 = wx.StaticBox( parent, -1, "Velocity vector" )
    item14 = wx.StaticBoxSizer( item15, wx.VERTICAL )

    item16 = wx.BoxSizer( wx.HORIZONTAL )

    item17 = wx.StaticText( parent, ID_TEXT, "X velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.TextCtrl( parent, ID_CENTER_VELOCITY_X, "", wx.DefaultPosition, [50,23], 0 )
    item16.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item14.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = wx.BoxSizer( wx.HORIZONTAL )

    item20 = wx.StaticText( parent, ID_TEXT, "Y velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.Add( item20, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item21 = wx.TextCtrl( parent, ID_CENTER_VELOCITY_Y, "", wx.DefaultPosition, [50,23], 0 )
    item19.Add( item21, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item14.Add( item19, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item22 = wx.CheckBox( parent, ID_CENTER_USE_VELOCITY, "use velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item22, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item13, 0, wx.ALIGN_CENTER, 0 )

    item23 = wx.BoxSizer( wx.HORIZONTAL )

    item24 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetDefault()
    item23.Add( item24, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item25 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item23.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item23, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_MAX_RIGHT = 10070
ID_MAX_LEFT = 10071
ID_MAX_UP = 10072
ID_MAX_DOWN = 10073
ID_MAX_RADIO_ANGLE = 10074
ID_MAX_ANGLE = 10075
ID_MAX_CONSTRAIN = 10076
ID_MAX_VELOCITY_X = 10077
ID_MAX_VELOCITY_Y = 10078
ID_MAX_USE_VELOCITY = 10079

def LocalMaxDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.StaticBox( parent, -1, "Direction" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )

    item4 = wx.RadioButton( parent, ID_MAX_RIGHT, "right", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.RadioButton( parent, ID_MAX_LEFT, "left", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.RadioButton( parent, ID_MAX_UP, "up", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.RadioButton( parent, ID_MAX_DOWN, "down", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )

    item9 = wx.RadioButton( parent, ID_MAX_RADIO_ANGLE, "angle:  ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.SHAPED, 5 )

    item10 = wx.TextCtrl( parent, ID_MAX_ANGLE, "", wx.DefaultPosition, [50,23], 0 )
    item8.Add( item10, 0, wx.ALIGN_CENTER, 5 )

    item2.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 0 )

    item11 = wx.CheckBox( parent, ID_MAX_CONSTRAIN, "Constrain to line", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item12 = wx.BoxSizer( wx.VERTICAL )

    item14 = wx.StaticBox( parent, -1, "Velocity vector" )
    item13 = wx.StaticBoxSizer( item14, wx.VERTICAL )

    item15 = wx.BoxSizer( wx.HORIZONTAL )

    item16 = wx.StaticText( parent, ID_TEXT, "X velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.TextCtrl( parent, ID_MAX_VELOCITY_X, "", wx.DefaultPosition, [50,23], 0 )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item13.Add( item15, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.BoxSizer( wx.HORIZONTAL )

    item19 = wx.StaticText( parent, ID_TEXT, "Y velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item20 = wx.TextCtrl( parent, ID_MAX_VELOCITY_Y, "", wx.DefaultPosition, [50,23], 0 )
    item18.Add( item20, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item13.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21 = wx.CheckBox( parent, ID_MAX_USE_VELOCITY, "use velocity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item21, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item12.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item22 = wx.BoxSizer( wx.HORIZONTAL )

    item23 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, [60,-1], 0 )
    item23.SetDefault()
    item22.Add( item23, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item24 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, [60,-1], 0 )
    item22.Add( item24, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item12.Add( item22, 0, wx.ALIGN_CENTER|wx.TOP, 15 )

    item1.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_MORPHO_TYPE = 10080
ID_ITERATIONS = 10081
ID_TEXT_ITERATIONS = 10082

def MorphologicalDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.RadioBox( parent, ID_MORPHO_TYPE, "Algorithms", wx.DefaultPosition, wx.DefaultSize,
        ["Erode","Dilate","Reconstruct","Outline","Skeleton","Hole fill","Hole extract","Border kill","Border line kill"] , 1, wx.RA_SPECIFY_COLS )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.ComboBox( parent, ID_ITERATIONS, "", wx.DefaultPosition, [60,-1],
        ["1","2","3","4","5","6","7","8","9"] , wx.CB_DROPDOWN )
    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT_ITERATIONS, "iterations", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )

    item6 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetDefault()
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_TEXT_WIDTH = 10083
ID_RESIZE_WIDTH = 10084
ID_TEXT_HEIGHT = 10085
ID_RESIZE_HEIGHT = 10086
ID_CONSTRAIN_ASPECT = 10087
ID_DIM_TYPE = 10088

def ResizeImageDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.StaticBox( parent, -1, "Dimensions" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )

    item4 = wx.BoxSizer( wx.HORIZONTAL )

    item5 = wx.StaticText( parent, ID_TEXT_WIDTH, "Width:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.TextCtrl( parent, ID_RESIZE_WIDTH, "", wx.DefaultPosition, [70,-1], 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )

    item8 = wx.StaticText( parent, ID_TEXT_HEIGHT, "Height:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = wx.TextCtrl( parent, ID_RESIZE_HEIGHT, "", wx.DefaultPosition, [70,-1], 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.BoxSizer( wx.VERTICAL )

    item11 = wx.CheckBox( parent, ID_CONSTRAIN_ASPECT, "Constrain aspect ratio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item12 = wx.ComboBox( parent, ID_DIM_TYPE, "", wx.DefaultPosition, [100,-1],
        ["pixels","percent"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item10.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item1.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item13 = wx.BoxSizer( wx.HORIZONTAL )

    item14 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetDefault()
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_EXTRACT_FIELD = 10089

def ExtractFieldDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.RadioBox( parent, ID_EXTRACT_FIELD, "Extract", wx.DefaultPosition, wx.DefaultSize,
        ["Odd field","Even field","Swap field order"] , 1, wx.RA_SPECIFY_COLS )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, [60,-1], 0 )
    item3.SetDefault()
    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, [60,-1], 0 )
    item2.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_BOTH_FIELDS = 10090
ID_ODD_FIRST = 10091
ID_EVEN_FIRST = 10092
ID_STEP_SIZE = 10093
ID_SS_TEXT = 10094
ID_FRAMESTOTRACK = 10095
ID_NFT_TEXT = 10096

def NextStepOptionsDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Step between" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )

    item3 = wx.RadioButton( parent, ID_BOTH_FIELDS, "frames (both fields)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetToolTip( wx.ToolTip("maintains 1 image frame for each video frame") )
    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.RadioButton( parent, ID_ODD_FIRST, "fields (odd first)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetToolTip( wx.ToolTip("2 image frames per each video frame") )
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5 = wx.RadioButton( parent, ID_EVEN_FIRST, "fields (even first)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetToolTip( wx.ToolTip("2 image frames per each video frame") )
    item1.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.BoxSizer( wx.VERTICAL )

    item7 = wx.BoxSizer( wx.HORIZONTAL )

    item8 = wx.TextCtrl( parent, ID_STEP_SIZE, "", wx.DefaultPosition, [60,-1], 0 )
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item9 = wx.StaticText( parent, ID_SS_TEXT, "Step size", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item6.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item10 = wx.BoxSizer( wx.HORIZONTAL )

    item11 = wx.TextCtrl( parent, ID_FRAMESTOTRACK, "", wx.DefaultPosition, [60,-1], 0 )
    item10.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item12 = wx.StaticText( parent, ID_NFT_TEXT, "Frames to track", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item12, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item6.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "Total = (StepSize x FramesToTrack)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item13, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item14 = wx.BoxSizer( wx.HORIZONTAL )

    item15 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetDefault()
    item14.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_SLIDER1_TEXT = 10097
ID_SLIDER1 = 10098
ID_SLIDER2_TEXT = 10099
ID_SLIDER2 = 10100
ID_SLIDER3_TEXT = 10101
ID_SLIDER3 = 10102
ID_APPLY = 10103

def AdaptiveThresholdDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item3 = wx.StaticBox( parent, -1, "Levels" )
    item2 = wx.StaticBoxSizer( item3, wx.HORIZONTAL )

    item4 = wx.BoxSizer( wx.VERTICAL )

    item5 = wx.StaticText( parent, ID_TEXT, "width", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item6 = wx.StaticText( parent, ID_TEXT, "height", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item7 = wx.StaticText( parent, ID_TEXT, "offset", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item7, 0, wx.ALIGN_CENTER|wx.TOP, 10 )

    item2.Add( item4, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item8 = wx.BoxSizer( wx.VERTICAL )

    item9 = wx.BoxSizer( wx.HORIZONTAL )

    item10 = wx.TextCtrl( parent, ID_SLIDER1_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item11 = wx.Slider( parent, ID_SLIDER1, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item12 = wx.BoxSizer( wx.HORIZONTAL )

    item13 = wx.TextCtrl( parent, ID_SLIDER2_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item12.Add( item13, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item14 = wx.Slider( parent, ID_SLIDER2, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item12.Add( item14, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item12, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item15 = wx.BoxSizer( wx.HORIZONTAL )

    item16 = wx.TextCtrl( parent, ID_SLIDER3_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item17 = wx.Slider( parent, ID_SLIDER3, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item15, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item2.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP, 5 )

    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.BoxSizer( wx.VERTICAL )

    item19 = wx.Button( parent, ID_APPLY, "Apply", wx.DefaultPosition, [60,-1], 0 )
    item18.Add( item19, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item18.Add( [ 20, 13 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item20 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, [60,-1], 0 )
    item20.SetDefault()
    item18.Add( item20, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item21 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, [60,-1], 0 )
    item18.Add( item21, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item1.Add( item18, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_CONVERT_COLOR = 10104

def ConvertPage1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.RadioBox( parent, ID_CONVERT_COLOR, "Type selection", wx.DefaultPosition, wx.DefaultSize,
        ["convert grayscale to color","convert color to grayscale"] , 1, wx.RA_SPECIFY_COLS )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_CONVERT_DEPTH = 10105

def ConvertPage2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.RadioBox( parent, ID_CONVERT_DEPTH, "Depth selection", wx.DefaultPosition, wx.DefaultSize,
        ["convert (force) to 16 bit","convert to 8 bit"] , 1, wx.RA_SPECIFY_COLS )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_CONVERT_DIALOG = 10106

def ConvertDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.Notebook( parent, ID_CONVERT_DIALOG, wx.DefaultPosition, [220,120], 0 )
    if wx.VERSION >= (2,5,2):
        item1 = item2
    else:
        item1 = wx.NotebookSizer( item2 )

    item3 = wx.Panel( item2, -1 )
    ConvertPage1Func(item3, False)
    item2.AddPage( item3, "Type" )

    item4 = wx.Panel( item2, -1 )
    ConvertPage2Func(item4, False)
    item2.AddPage( item4, "Depth" )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )

    item6 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetDefault()
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_TEXT_BASENAME = 10107
ID_BASEFILE = 10108
ID_TEXT_EXT = 10109
ID_FILE_EXT = 10110
ID_BASEFILE_SEL = 10111
ID_CHECK_APPNUMB = 10112
ID_APPEND_NUMB = 10113
ID_SAVEAS_GRAY = 10114

def SaveAoiDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticText( parent, ID_TEXT_BASENAME, "Base name:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )

    item4 = wx.TextCtrl( parent, ID_BASEFILE, "", wx.DefaultPosition, [230,-1], 0 )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )

    item6 = wx.StaticText( parent, ID_TEXT_EXT, "Image type (ext):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item7 = wx.ComboBox( parent, ID_FILE_EXT, "", wx.DefaultPosition, [60,-1],
        [".tif",".jpg",".png",".bmp"] , wx.CB_DROPDOWN )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = wx.Button( parent, ID_BASEFILE_SEL, "Select", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item9 = wx.BoxSizer( wx.VERTICAL )

    item10 = wx.BoxSizer( wx.HORIZONTAL )

    item11 = wx.CheckBox( parent, ID_CHECK_APPNUMB, "Append number:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item12 = wx.TextCtrl( parent, ID_APPEND_NUMB, "", wx.DefaultPosition, [80,-1], 0 )
    item10.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item13 = wx.BoxSizer( wx.VERTICAL )

    item14 = wx.CheckBox( parent, ID_SAVEAS_GRAY, "Save as grayscale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9.Add( item13, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item0.Add( item9, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = wx.BoxSizer( wx.HORIZONTAL )

    item16 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.SetDefault()
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item15, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_TEXT_X1 = 10115
ID_X1 = 10116
ID_TEXT_Y1 = 10117
ID_Y1 = 10118
ID_TEXT_X2 = 10119
ID_X2 = 10120
ID_TEXT_Y2 = 10121
ID_Y2 = 10122
ID_POS_SAVE = 10123
ID_POS_LOAD = 10124

def AoiPositionDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item2 = wx.StaticText( parent, ID_TEXT_X1, "x1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3 = wx.TextCtrl( parent, ID_X1, "", wx.DefaultPosition, [50,-1], 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.StaticText( parent, ID_TEXT_Y1, "y1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.TextCtrl( parent, ID_Y1, "", wx.DefaultPosition, [50,-1], 0 )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )

    item7 = wx.StaticText( parent, ID_TEXT_X2, "x2:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.TextCtrl( parent, ID_X2, "", wx.DefaultPosition, [50,-1], 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item9 = wx.StaticText( parent, ID_TEXT_Y2, "y2:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.TextCtrl( parent, ID_Y2, "", wx.DefaultPosition, [50,-1], 0 )
    item6.Add( item10, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item11 = wx.BoxSizer( wx.VERTICAL )

    item12 = wx.Button( parent, ID_POS_SAVE, "Save", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item13 = wx.Button( parent, ID_POS_LOAD, "Load", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item14 = wx.BoxSizer( wx.HORIZONTAL )

    item15 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetDefault()
    item14.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item14, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_FACTOR = 10125
ID_FACTOR_SLIDER = 10126

def TestDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Levels" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )

    item3 = wx.BoxSizer( wx.VERTICAL )

    item4 = wx.StaticText( parent, ID_TEXT, "Color", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "Brightness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item6 = wx.StaticText( parent, ID_TEXT, "Contrast", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item7 = wx.StaticText( parent, ID_TEXT, "Sharpness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item7, 0, wx.ALIGN_CENTER|wx.TOP, 10 )

    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.BOTTOM, 0 )

    item8 = wx.BoxSizer( wx.VERTICAL )

    item9 = wx.BoxSizer( wx.HORIZONTAL )

    item10 = wx.TextCtrl( parent, ID_SLIDER1_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item11 = wx.Slider( parent, ID_SLIDER1, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item12 = wx.BoxSizer( wx.HORIZONTAL )

    item13 = wx.TextCtrl( parent, ID_SLIDER2_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item12.Add( item13, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item14 = wx.Slider( parent, ID_SLIDER2, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item12.Add( item14, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item12, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item15 = wx.BoxSizer( wx.HORIZONTAL )

    item16 = wx.TextCtrl( parent, ID_SLIDER3_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item17 = wx.Slider( parent, ID_SLIDER3, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item15, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item18 = wx.BoxSizer( wx.HORIZONTAL )

    item19 = wx.TextCtrl( parent, ID_SLIDER2_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item18.Add( item19, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item20 = wx.Slider( parent, ID_SLIDER2, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item18.Add( item20, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item8.Add( item18, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item1.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item22 = wx.StaticBox( parent, -1, "Levels" )
    item21 = wx.StaticBoxSizer( item22, wx.VERTICAL )

    item23 = wx.BoxSizer( wx.HORIZONTAL )

    item24 = wx.TextCtrl( parent, ID_FACTOR, "", wx.DefaultPosition, [40,-1], 0 )
    item23.Add( item24, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item25 = wx.Slider( parent, ID_FACTOR_SLIDER, 1, 0, 10, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item23.Add( item25, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item26 = wx.StaticText( parent, ID_TEXT, "Color", wx.DefaultPosition, [61,-1], 0 )
    item23.Add( item26, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item21.Add( item23, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item27 = wx.BoxSizer( wx.HORIZONTAL )

    item28 = wx.TextCtrl( parent, ID_FACTOR, "", wx.DefaultPosition, [40,-1], 0 )
    item27.Add( item28, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item29 = wx.Slider( parent, ID_FACTOR_SLIDER, 1, 0, 10, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item27.Add( item29, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item30 = wx.StaticText( parent, ID_TEXT, "Brightness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item30, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item21.Add( item27, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item31 = wx.BoxSizer( wx.HORIZONTAL )

    item32 = wx.TextCtrl( parent, ID_FACTOR, "", wx.DefaultPosition, [40,-1], 0 )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item33 = wx.Slider( parent, ID_FACTOR_SLIDER, 1, 0, 10, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item31.Add( item33, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item34 = wx.StaticText( parent, ID_TEXT_LEVEL, "Contrast", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item34, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item21.Add( item31, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item35 = wx.BoxSizer( wx.HORIZONTAL )

    item36 = wx.TextCtrl( parent, ID_FACTOR, "", wx.DefaultPosition, [40,-1], 0 )
    item35.Add( item36, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item37 = wx.Slider( parent, ID_FACTOR_SLIDER, 1, 0, 10, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item35.Add( item37, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item38 = wx.StaticText( parent, ID_TEXT_LEVEL, "Sharpness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.Add( item38, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item21.Add( item35, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item21, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item40 = wx.StaticBox( parent, -1, "Levels" )
    item39 = wx.StaticBoxSizer( item40, wx.HORIZONTAL )

    item41 = wx.BoxSizer( wx.VERTICAL )

    item42 = wx.StaticText( parent, ID_TEXT, "Color", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item42, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item43 = wx.StaticText( parent, ID_TEXT, "Brightness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item43, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item44 = wx.StaticText( parent, ID_TEXT, "Contrast", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item44, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 10 )

    item45 = wx.StaticText( parent, ID_TEXT, "Sharpness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item45, 0, wx.ALIGN_CENTER|wx.TOP, 10 )

    item39.Add( item41, 0, wx.ALIGN_CENTER|wx.BOTTOM, 0 )

    item46 = wx.BoxSizer( wx.VERTICAL )

    item47 = wx.BoxSizer( wx.HORIZONTAL )

    item48 = wx.Slider( parent, ID_SLIDER1, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item47.Add( item48, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item49 = wx.TextCtrl( parent, ID_SLIDER1_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item47.Add( item49, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item46.Add( item47, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item50 = wx.BoxSizer( wx.HORIZONTAL )

    item51 = wx.Slider( parent, ID_SLIDER2, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item50.Add( item51, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item52 = wx.TextCtrl( parent, ID_SLIDER2_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item50.Add( item52, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item46.Add( item50, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item53 = wx.BoxSizer( wx.HORIZONTAL )

    item54 = wx.Slider( parent, ID_SLIDER3, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item53.Add( item54, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item55 = wx.TextCtrl( parent, ID_SLIDER3_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item53.Add( item55, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item46.Add( item53, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item56 = wx.BoxSizer( wx.HORIZONTAL )

    item57 = wx.Slider( parent, ID_SLIDER2, 1, 1, 12, wx.DefaultPosition, [128,-1], wx.SL_HORIZONTAL|wx.SL_AUTOTICKS )
    item56.Add( item57, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item58 = wx.TextCtrl( parent, ID_SLIDER2_TEXT, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item56.Add( item58, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item46.Add( item56, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item39.Add( item46, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP, 5 )

    item0.Add( item39, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item59 = wx.BoxSizer( wx.HORIZONTAL )

    item60 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetDefault()
    item59.Add( item60, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item61 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.Add( item61, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item59, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_OPTIONS_DIALOG = 10127

def OptionsDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.Notebook( parent, ID_OPTIONS_DIALOG, wx.DefaultPosition, [400,190], 0 )
    if wx.VERSION >= (2,5,2):
        item1 = item2
    else:
        item1 = wx.NotebookSizer( item2 )

    item3 = wx.Panel( item2, -1 )
    OptionsPage1Func(item3, False)
    item2.AddPage( item3, "General Options" )

    item4 = wx.Panel( item2, -1 )
    OptionsPage2Func(item4, False)
    item2.AddPage( item4, "Pixel Display Type" )

    item5 = wx.Panel( item2, -1 )
    OptionsPage3Func(item5, False)
    item2.AddPage( item5, "Pseudocolor" )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )

    item7 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetDefault()
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_BACKGROUND_COLORS = 10128
ID_TEXT_B_COLORS = 10129
ID_SQUARE_PIXELS = 10130
ID_ARBITRARY_ASPECT = 10131
ID_ASPECT_RATIO = 10132

def OptionsPage1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item2 = wx.Choice( parent, ID_BACKGROUND_COLORS, wx.DefaultPosition, [100,-1],
        ["white","light gray","gray","wheat","light blue"] , 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3 = wx.StaticText( parent, ID_TEXT_B_COLORS, "Background color", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 10 )

    item5 = wx.StaticBox( parent, -1, "Correct image width to make square pixels" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )

    item6 = wx.BoxSizer( wx.HORIZONTAL )

    item7 = wx.CheckBox( parent, ID_SQUARE_PIXELS, "Convert DV (720x480) to square pixels (640x480)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER, 5 )

    item4.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )

    item9 = wx.CheckBox( parent, ID_ARBITRARY_ASPECT, "Scale to arbitrary width in pixels:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.TextCtrl( parent, ID_ASPECT_RATIO, "", wx.DefaultPosition, [65,-1], 0 )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item4.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_PIXEL_TYPE = 10133

def OptionsPage2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.RadioBox( parent, ID_PIXEL_TYPE, "Display Pixel Values As:", wx.DefaultPosition, wx.DefaultSize,
        ["Normalized values","Actual values"] , 1, wx.RA_SPECIFY_COLS )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 20 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 15 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_BRIGHTNESS_SLIDER = 10134
ID_BRIGHTNESS = 10135
ID_CONTRAST_SLIDER = 10136
ID_CONTRAST = 10137
ID_COLOR_SLIDER = 10138
ID_COLOR = 10139
ID_SHARPNESS_SLIDER = 10140
ID_SHARPNESS = 10141

def EnhanceDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Levels" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )

    item3 = wx.FlexGridSizer( 0, 3, 6, 0 )

    item4 = wx.StaticText( parent, ID_TEXT, "Brightness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item5 = wx.Slider( parent, ID_BRIGHTNESS_SLIDER, 0, 1, 200, wx.DefaultPosition, [200,-1], wx.SL_HORIZONTAL )
    item3.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.TextCtrl( parent, ID_BRIGHTNESS, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item7 = wx.StaticText( parent, ID_TEXT, "Contrast", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item8 = wx.Slider( parent, ID_CONTRAST_SLIDER, 0, 1, 200, wx.DefaultPosition, [200,-1], wx.SL_HORIZONTAL )
    item3.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.TextCtrl( parent, ID_CONTRAST, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item3.Add( item9, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item10 = wx.StaticText( parent, ID_TEXT, "Color", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item11 = wx.Slider( parent, ID_COLOR_SLIDER, 0, 0, 100, wx.DefaultPosition, [200,-1], wx.SL_HORIZONTAL )
    item3.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item12 = wx.TextCtrl( parent, ID_COLOR, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item3.Add( item12, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item13 = wx.StaticText( parent, ID_TEXT, "Sharpness", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item13, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item14 = wx.Slider( parent, ID_SHARPNESS_SLIDER, 0, 0, 100, wx.DefaultPosition, [200,-1], wx.SL_HORIZONTAL )
    item3.Add( item14, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.TextCtrl( parent, ID_SHARPNESS, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item3.Add( item15, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.BoxSizer( wx.HORIZONTAL )

    item17 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.SetDefault()
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_PALETTE_FILE = 10142
ID_SELECT_PALETTE = 10143
ID_APPLY_PALETTE = 10144

def OptionsPage3Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticText( parent, ID_TEXT, "Palette file:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )

    item4 = wx.TextCtrl( parent, ID_PALETTE_FILE, "", wx.DefaultPosition, [240,23], 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.Button( parent, ID_SELECT_PALETTE, "Select", wx.DefaultPosition, [50,-1], 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER, 5 )

    item6 = wx.CheckBox( parent, ID_APPLY_PALETTE, "Apply palette to display", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP, 15 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_LEFT_PANEL = 10145
ID_TOP_PANEL = 10146
ID_GRAPH_PANEL = 10147
ID_LL_PANEL = 10148
ID_RIGHT_PANEL = 10149
ID_L_THICKNESS = 10150
ID_LOCK_AXIS = 10151
ID_BUTTON_SVF = 10152
ID_BUTTON_INT = 10153

def AbelDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item2 = wx.BoxSizer( wx.VERTICAL )

    item3 = wx.Panel( parent, ID_LEFT_PANEL, wx.DefaultPosition, [50,240], 0 )
    item2.Add( item3, 0, wx.ALIGN_CENTER, 0 )

    item1.Add( item2, 0, wx.ALIGN_CENTER, 5 )

    item4 = wx.BoxSizer( wx.VERTICAL )

    item5 = wx.Panel( parent, ID_TOP_PANEL, wx.DefaultPosition, [320,20], 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER, 5 )

    item6 = wx.Panel( parent, ID_GRAPH_PANEL, wx.DefaultPosition, [320,200], 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER, 5 )

    item7 = wx.Panel( parent, ID_LL_PANEL, wx.DefaultPosition, [320,20], 0 )
    item4.Add( item7, 0, wx.ALIGN_CENTER, 5 )

    item1.Add( item4, 0, wx.ALIGN_CENTER, 5 )

    item8 = wx.BoxSizer( wx.VERTICAL )

    item9 = wx.Panel( parent, ID_RIGHT_PANEL, wx.DefaultPosition, [50,240], 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER, 0 )

    item1.Add( item8, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER, 0 )

    item10 = wx.BoxSizer( wx.HORIZONTAL )

    item11 = wx.BoxSizer( wx.HORIZONTAL )

    item12 = wx.BoxSizer( wx.VERTICAL )

    item13 = wx.StaticText( parent, ID_TEXT, "line", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item13, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item14 = wx.StaticText( parent, ID_TEXT, "thickness:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item14, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item11.Add( item12, 0, wx.ALIGN_CENTER, 5 )

    item15 = wx.SpinCtrl( parent, ID_L_THICKNESS, "1", wx.DefaultPosition, [50,23], 0, 1, 200, 1 )
    item11.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11.Add( [ 40, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.CheckBox( parent, ID_LOCK_AXIS, "lock x-axis movement", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10.Add( item11, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item10, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item17 = wx.BoxSizer( wx.HORIZONTAL )

    item18 = wx.Button( parent, ID_BUTTON_SVF, "SVF", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.Button( parent, ID_BUTTON_INT, "Intensity", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17.Add( [ 60, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item20 = wx.Button( parent, wx.ID_CANCEL, "Close", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetDefault()
    item17.Add( item20, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_ABEL_FILTERS = 10154
ID_ABELTEXT1 = 10155
ID_ABELTEXT2 = 10156
ID_ABEL_RANGE = 10157
ID_ABELTEXT3 = 10158
ID_ABEL_SMOOTHING_FACTOR = 10159
ID_ABEL_AVERAGING = 10160
ID_SVF_SEPARATION = 10161

def GeneralAbelOptionsDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.RadioBox( parent, ID_ABEL_FILTERS, "Abel Filters", wx.DefaultPosition, wx.DefaultSize,
        ["Direct Abel transform - no filtering","Low pass - maximum # of periods in the whole domain","Smoothing w/ a 2 grid side window in the physical domain","Smoothing w/ a 4 grid side window in the physical domain"] , 1, wx.RA_SPECIFY_COLS )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )

    item5 = wx.StaticBox( parent, -1, "Smoothing Factor" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )

    item6 = wx.StaticText( parent, ID_ABELTEXT1,
        "The smoothing factor is the\n"
        "characteristic wave number of the\n"
        "filter. The larger the number,\n"
        "the higher the cut-off frequency.",
        wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )

    item8 = wx.StaticText( parent, ID_ABELTEXT2, "It should be between 1.0 and", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item9 = wx.TextCtrl( parent, ID_ABEL_RANGE, "", wx.DefaultPosition, [40,-1], wx.TE_READONLY )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item4.Add( item7, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item10 = wx.BoxSizer( wx.HORIZONTAL )

    item11 = wx.StaticText( parent, ID_ABELTEXT3, "Smoothing factor:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item11, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item12 = wx.TextCtrl( parent, ID_ABEL_SMOOTHING_FACTOR, "", wx.DefaultPosition, [40,-1], 0 )
    item10.Add( item12, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item4.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item13 = wx.BoxSizer( wx.VERTICAL )

    item14 = wx.RadioBox( parent, ID_ABEL_AVERAGING, "Averaging Option", wx.DefaultPosition, wx.DefaultSize,
        ["average both sides","calculate each side separately"] , 1, wx.RA_SPECIFY_COLS )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.BoxSizer( wx.HORIZONTAL )

    item16 = wx.TextCtrl( parent, ID_SVF_SEPARATION, "", wx.DefaultPosition, [60,-1], 0 )
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "pixel separation (mm)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item13.Add( item15, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item3.Add( item13, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item18 = wx.BoxSizer( wx.HORIZONTAL )

    item19 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetDefault()
    item18.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item20 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.Add( item20, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_SVF_WAVELENGTH = 10162
ID_SVF_SRI = 10163
ID_SVF_BACKG1 = 10164
ID_SVF_LEFT = 10165
ID_SVF_LEFT_TEXT = 10166
ID_SVF_RIGHT = 10167
ID_SVF_RIGHT_TEXT = 10168
ID_SVF_BACKG2 = 10169
ID_SVF_REF_IMAGE = 10170
ID_SVF_SEL_RI = 10171

def SvfAbelOptionsDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Physical Parameters" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )

    item3 = wx.BoxSizer( wx.HORIZONTAL )

    item4 = wx.TextCtrl( parent, ID_SVF_WAVELENGTH, "", wx.DefaultPosition, [80,-1], 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "wavelength (nm)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )

    item7 = wx.TextCtrl( parent, ID_SVF_SRI, "", wx.DefaultPosition, [80,-1], 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "soot refractive index", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item1.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.StaticBox( parent, -1, "Background Selection" )
    item9 = wx.StaticBoxSizer( item10, wx.VERTICAL )

    item11 = wx.BoxSizer( wx.HORIZONTAL )

    item12 = wx.RadioButton( parent, ID_SVF_BACKG1, "background (ends of Abel tool)", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item11.Add( item12, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item13 = wx.TextCtrl( parent, ID_SVF_LEFT, "", wx.DefaultPosition, [80,-1], 0 )
    item11.Add( item13, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item14 = wx.StaticText( parent, ID_SVF_LEFT_TEXT, "left", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item14, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item15 = wx.TextCtrl( parent, ID_SVF_RIGHT, "", wx.DefaultPosition, [80,-1], 0 )
    item11.Add( item15, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item16 = wx.StaticText( parent, ID_SVF_RIGHT_TEXT, "right", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item16, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item9.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item17 = wx.BoxSizer( wx.HORIZONTAL )

    item18 = wx.RadioButton( parent, ID_SVF_BACKG2, "reference image:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item18, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = wx.TextCtrl( parent, ID_SVF_REF_IMAGE, "", wx.DefaultPosition, [240,-1], 0 )
    item17.Add( item19, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.Button( parent, ID_SVF_SEL_RI, "Select", wx.DefaultPosition, [50,-1], 0 )
    item17.Add( item20, 0, wx.ALIGN_CENTER, 5 )

    item9.Add( item17, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item21 = wx.BoxSizer( wx.HORIZONTAL )

    item22 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetDefault()
    item21.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item23 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item23, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item21, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_FIXED_ASPECT = 10172

def RectangleAoiOptionsDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Aoi Size" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )

    item3 = wx.BoxSizer( wx.VERTICAL )

    item4 = wx.BoxSizer( wx.HORIZONTAL )

    item5 = wx.StaticText( parent, ID_TEXT_WIDTH, "Width:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.TextCtrl( parent, ID_RESIZE_WIDTH, "", wx.DefaultPosition, [70,-1], 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )

    item8 = wx.StaticText( parent, ID_TEXT_HEIGHT, "Height:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.TextCtrl( parent, ID_RESIZE_HEIGHT, "", wx.DefaultPosition, [70,-1], 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item3.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item10 = wx.CheckBox( parent, ID_FIXED_ASPECT, "Fixed aspect ratio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.BoxSizer( wx.HORIZONTAL )

    item12 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetDefault()
    item11.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0


def RectAoiOptionsDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticBox( parent, -1, "Fixed aspect ratio" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )

    item3 = wx.StaticText( parent, ID_TEXT,
        "The width and height below specify the\n"
        "fixed aspect ratio to which the Aoi can \n"
        "be resized. The resizing of the Aoi to the\n"
        "fixed aspect ratio is done by dragging the \n"
        "lower-right corner of the box while pressing\n"
        "the Control key.",
        wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.BoxSizer( wx.VERTICAL )

    item5 = wx.BoxSizer( wx.HORIZONTAL )

    item6 = wx.StaticText( parent, ID_TEXT_WIDTH, "Relative width:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.TextCtrl( parent, ID_RESIZE_WIDTH, "", wx.DefaultPosition, [70,-1], 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )

    item9 = wx.StaticText( parent, ID_TEXT_HEIGHT, "Relative height:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.TextCtrl( parent, ID_RESIZE_HEIGHT, "", wx.DefaultPosition, [70,-1], 0 )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item4.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.BoxSizer( wx.HORIZONTAL )

    item12 = wx.Button( parent, wx.ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetDefault()
    item11.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.Button( parent, wx.ID_CANCEL, "Cancel", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_PIXEL_NUMBER = 10173
ID_LINE_LENGTH = 10174
ID_SAVE_BUTTON = 10175
ID_RED_BUTTON = 10176
ID_GREEN_BUTTON = 10177
ID_BLUE_BUTTON = 10178
ID_LUMINANCE_BUTTON = 10179
ID_RGB_BUTTON = 10180
ID_HUE_BUTTON = 10181

def LineProfileDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.Panel( parent, ID_GRAPH_PANEL, wx.DefaultPosition, [360,225], wx.SUNKEN_BORDER )
    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )

    item4 = wx.BoxSizer( wx.HORIZONTAL )

    item5 = wx.BoxSizer( wx.VERTICAL )

    item6 = wx.StaticText( parent, ID_TEXT, "line", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "thickness:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item4.Add( item5, 0, wx.ALIGN_CENTER, 5 )

    item8 = wx.SpinCtrl( parent, ID_L_THICKNESS, "1", wx.DefaultPosition, [55,23], 0, 1, 200, 1 )
    item4.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )

    item10 = wx.StaticText( parent, ID_TEXT, "pixels:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item11 = wx.TextCtrl( parent, ID_PIXEL_NUMBER, "", wx.DefaultPosition, [40,23], wx.TE_READONLY )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 0 )

    item12 = wx.BoxSizer( wx.HORIZONTAL )

    item13 = wx.StaticText( parent, ID_TEXT, "line lenght:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item13, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item14 = wx.TextCtrl( parent, ID_LINE_LENGTH, "", wx.DefaultPosition, [56,23], wx.TE_READONLY )
    item12.Add( item14, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item3.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item15 = wx.BoxSizer( wx.HORIZONTAL )

    item16 = wx.Button( parent, ID_SAVE_BUTTON, "Save", wx.DefaultPosition, [55,25], 0 )
    item15.Add( item16, 1, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item17 = wx.BoxSizer( wx.HORIZONTAL )

    item18 = wx.Button( parent, ID_RED_BUTTON, "R", wx.DefaultPosition, [35,25], 0 )
    item17.Add( item18, 0, wx.ALIGN_CENTER, 0 )

    item19 = wx.Button( parent, ID_GREEN_BUTTON, "G", wx.DefaultPosition, [35,25], 0 )
    item17.Add( item19, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item20 = wx.Button( parent, ID_BLUE_BUTTON, "B", wx.DefaultPosition, [35,25], 0 )
    item17.Add( item20, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item21 = wx.Button( parent, ID_LUMINANCE_BUTTON, "L", wx.DefaultPosition, [35,25], 0 )
    item17.Add( item21, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item22 = wx.Button( parent, ID_RGB_BUTTON, "RGB", wx.DefaultPosition, [45,25], 0 )
    item17.Add( item22, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item23 = wx.Button( parent, ID_HUE_BUTTON, "H", wx.DefaultPosition, [35,25], 0 )
    item17.Add( item23, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 0 )

    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item24 = wx.Button( parent, wx.ID_CANCEL, "Close", wx.DefaultPosition, [55,25], 0 )
    item24.SetDefault()
    item15.Add( item24, 1, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item1.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_BUTTON = 10182

def PanelDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.HORIZONTAL )

    item2 = wx.Button( parent, ID_BUTTON, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.Button( parent, ID_BUTTON, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item3, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.Button( parent, ID_BUTTON, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0


def HistogramNewDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.Panel( parent, ID_GRAPH_PANEL, wx.DefaultPosition, [390,260], wx.SUNKEN_BORDER )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )

    item4 = wx.Button( parent, ID_SAVE_BUTTON, "Save", wx.DefaultPosition, [55,25], 0 )
    item3.Add( item4, 1, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item3.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )

    item6 = wx.Button( parent, ID_RED_BUTTON, "R", wx.DefaultPosition, [35,25], 0 )
    item5.Add( item6, 0, wx.ALIGN_CENTER, 0 )

    item7 = wx.Button( parent, ID_GREEN_BUTTON, "G", wx.DefaultPosition, [35,25], 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item8 = wx.Button( parent, ID_BLUE_BUTTON, "B", wx.DefaultPosition, [35,25], 0 )
    item5.Add( item8, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item9 = wx.Button( parent, ID_LUMINANCE_BUTTON, "L", wx.DefaultPosition, [35,25], 0 )
    item5.Add( item9, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 0 )

    item5.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.Button( parent, wx.ID_CANCEL, "Close", wx.DefaultPosition, [55,25], 0 )
    item10.SetDefault()
    item3.Add( item10, 1, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

ID_UNREADABLE_FILE = 10183
ID_LOG_FILE = 10184
ID_DONT_ASK = 10185

def TrackingFailedDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )

    item1 = wx.BoxSizer( wx.VERTICAL )

    item2 = wx.StaticText( parent, ID_TEXT, "Cannot read file:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item3 = wx.TextCtrl( parent, ID_UNREADABLE_FILE, "", wx.DefaultPosition, [280,-1], wx.TE_READONLY )
    item1.Add( item3, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Unreadable files are logged in:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.TextCtrl( parent, ID_LOG_FILE, "", wx.DefaultPosition, [280,-1], wx.TE_READONLY )
    item1.Add( item5, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )

    item7 = wx.Button( parent, wx.ID_CANCEL, "Stop", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetDefault()
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.Button( parent, wx.ID_OK, "Skip", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item9 = wx.CheckBox( parent, ID_DONT_ASK, "Don't Ask Again", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )

    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
